### ISSUE TITLE
Tracking issue: dashboard

### ISSUE THREAD

**Issue by timvisee** [kwint/nfc-card-game#10]
#### Tasks
- [x] Limit miner instances on screen, drop old ones  
      <https://github.com/kwint/nfc-card-game/pull/15>)
- [x] Add miner added animation  
      <https://github.com/kwint/nfc-card-game/pull/13>
- [x] Add money increase animation
      <https://github.com/kwint/nfc-card-game/pull/13>
- [x] Dashboard: improve miner placement  
      https://github.com/kwint/nfc-card-game/pull/17
- [x] Server: expose miner effectiveness rather than quantity
      <https://github.com/kwint/nfc-card-game/pull/20>
- [x] Server: when broadcasting added miners, set proper miner type  
      <https://github.com/kwint/nfc-card-game/pull/22>
- [x] Dashboard: handle websocket failures  
      <https://github.com/kwint/nfc-card-game/pull/25>
- [x] Dashboard: handle HTTP request failures  
      <https://github.com/kwint/nfc-card-game/pull/25>
- [x] Dashboard: improve mountain textures
      <https://github.com/kwint/nfc-card-game/pull/26>
- [x] Dashboard: add button to switch mine at runtime
      <https://github.com/kwint/nfc-card-game/pull/27>
- [x] Dashboard: add button to refresh/reconnect
      <https://github.com/kwint/nfc-card-game/pull/27>
- [x] Dashboard: full screen
      <https://github.com/kwint/nfc-card-game/pull/28>
- [x] Dashboard: add icon
      <https://github.com/kwint/nfc-card-game/pull/29>
- [x] Dashboard: improve GUI components (balance description, money position)  
      <https://github.com/kwint/nfc-card-game/pull/31>
- [x] Dashboard: spawn at most 500 at once?  
      <https://github.com/kwint/nfc-card-game/pull/33>
- [x] Dashboard: configure globals through env vars  
      <https://github.com/kwint/nfc-card-game/pull/37>
- [x] Dashboard: find better miner sprites

#### Backlog
Done
